apiVersion: v2
description: A Helm chart for a Conference Platform App
name: fmtok8s-app
version: 0.0.104
type: application
icon: https://rawgit.com/jenkins-x/jenkins-x-platform/08df980/images/kubernetes.png
appVersion: 1.0.0
maintainers: 
  - name: salaboy
    email: salaboy@gmail.com
    url: http://salaboy.com
home: http://github.com/salaboy/from-monolith-to-k8s    
keywords:
  - cloudnative
  - example
  - cd
  - kubernetes
  - tutorial
dependencies:
- name: fmtok8s-api-gateway
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.140
- name: fmtok8s-agenda-rest
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.9
- name: fmtok8s-c4p-rest
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.14
- name: fmtok8s-email-rest
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.9
