# Default values for Conference.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fmtok8s-agenda:
  knativeDeploy: true
  #externalSecretForZeebe: true

fmtok8s-c4p:
  knativeDeploy: true
  #externalSecretForZeebe: true

fmtok8s-email:
  knativeDeploy: true
  #externalSecretForZeebe: true
fmtok8s-api-gateway:
  knativeDeploy: true
 # externalSecretForZeebe: true
  env:
    AGENDA_SERVICE: http://fmtok8s-agenda.default.svc.cluster.local
    C4P_SERVICE: http://fmtok8s-c4p.default.svc.cluster.local
    EMAIL_SERVICE: http://fmtok8s-email.default.svc.cluster.local
    SPEAKERS_SERVICE: http://fmtok8s-speakers.default.svc.cluster.local
fmtok8s-speakers:
  knativeDeploy: true
  #externalSecretForZeebe: true

#zeebe-cloud-events-router:
#  knativeDeploy: false
#  externalSecretForZeebe: true